### ISSUE TITLE
Sub pages?

### ISSUE THREAD

**Issue by Zeryther** [njb-said/webserver#4]
How do we do Subpages?

**Comment by njb-said** [comment]
What do you mean?

**Comment by Zeryther** [comment]
Like I do a class, which extends WebPage. That's like the index.html. How can I do another page, like subpage.html, which index.html links to?

**Comment by njb-said** [comment]
Take a look at [this](https://github.com/MC-API/a.vatar.co), it uses the dynamic mode where everything is generated by the Java classes, however if you want to use html files from your system like /index.html and /test/index.html you need to input a root path in the web page constructor.

I'm not great at explaining things :stuck_out_tongue:
